Repository tensorflow/tfx-addons, pull requests merged in 2021-09, with the labels that each got.

#72 Fix ci_examples and fix setup.py issues for CI
  .github/workflows/ci.yml
  .github/workflows/ci_examples.yml
  .github/workflows/lint.yml
  .gitignore
  examples/sklearn_penguins/penguin_pipeline_sklearn_gcp_test.py
  examples/sklearn_penguins/penguin_pipeline_sklearn_local_e2e_test.py
  examples/sklearn_penguins/requirements.txt
  examples/sklearn_penguins/sklearn_predict_extractor_test.py
  examples/xgboost_penguins/requirements.txt
  setup.py
Labels: lgtm, merge-ready

#75 Testing automerge!
  tfx_addons/mlmd_client/README.md
Labels: lgtm, merge-ready

#77 Add badges for both CI jobs
  README.md
Labels: needs-lgtm

#76 Add documentation for automerge and remove auto-assignation for PRs
  .github/workflows/automerge.yml
  CODEOWNERS
  CONTRIBUTING.md
Labels: lgtm, needs-merge

#81 Adding basic feast connection config
  projects/feature-store-connector/feast_example_gen/protos/FeastConfig.proto
  projects/feature-store-connector/feast_example_gen/protos/feast/core/CoreService.proto
  projects/feature-store-connector/feast_example_gen/protos/feast/core/DataFormat.proto
  projects/feature-store-connector/feast_example_gen/protos/feast/core/DataSource.proto
  projects/feature-store-connector/feast_example_gen/protos/feast/core/Entity.proto
  projects/feature-store-connector/feast_example_gen/protos/feast/core/Feature.proto
  projects/feature-store-connector/feast_example_gen/protos/feast/core/FeatureService.proto
  projects/feature-store-connector/feast_example_gen/protos/feast/core/FeatureTable.proto
  projects/feature-store-connector/feast_example_gen/protos/feast/core/FeatureView.proto
  projects/feature-store-connector/feast_example_gen/protos/feast/core/FeatureViewProjection.proto
  projects/feature-store-connector/feast_example_gen/protos/feast/core/OnDemandFeatureView.proto
  projects/feature-store-connector/feast_example_gen/protos/feast/core/Registry.proto
  projects/feature-store-connector/feast_example_gen/protos/feast/core/Store.proto
  projects/feature-store-connector/feast_example_gen/protos/feast/types/EntityKey.proto
  projects/feature-store-connector/feast_example_gen/protos/feast/types/Field.proto
  projects/feature-store-connector/feast_example_gen/protos/feast/types/Value.proto
Labels: needs-lgtm

#69 Project proposal for Firebase ML Publisher custom component
  proposals/20210817-firebase_ml_publisher_component.md
Labels: needs-lgtm
