Repository tensorflow/tfx-addons, pull requests merged in 2022-08, with the labels that each got.

#161 Add feature_selection to included pkg
  .github/ci/.pre-commit-config.yaml
  .github/ci/deps/requirements_max.in
  .github/ci/deps/requirements_min.in
  .github/license-templates/LICENSE.txt
  .github/workflows/ci.yml
  .github/workflows/filter_projects.py
  CONTRIBUTING.md
  examples/sklearn_penguins/requirements.txt
  tfx_addons/version.py
Labels: needs-lgtm

#155 PandasTransform - Ready for review
  CODEOWNERS
  examples/pandas_transform/pandas_transform_example.ipynb
  tfx_addons/pandas_transform/README.md
  tfx_addons/pandas_transform/RELEASE.md
  tfx_addons/pandas_transform/__init__.py
  tfx_addons/pandas_transform/component.py
  tfx_addons/pandas_transform/component_test.py
  tfx_addons/pandas_transform/null_preprocessing.py
  tfx_addons/version.py
Labels: lgtm, merge-ready

#162 support tfx 1.9
  tfx_addons/version.py
Labels: needs-lgtm

#164 small fix for filter projects
  .github/workflows/ci.yml
  .github/workflows/filter_projects.py
Labels: needs-lgtm

#165 Update README to add missing component
  README.md
Labels: needs-lgtm

#150 Added release notes for feature selection component
  tfx_addons/feature_selection/RELEASE.md
Labels: lgtm, needs-merge

#149 Added tests for feature selection component
  tfx_addons/feature_selection/component.py
  tfx_addons/feature_selection/component_test.py
  tfx_addons/feature_selection/requirements.txt
  tfx_addons/feature_selection/test/iris.csv
  tfx_addons/version.py
Labels: lgtm, merge-ready

#166 Improve examples CI to automatically pick up projects
  .github/workflows/ci_examples.yml
  .github/workflows/filter_examples.py
  .github/workflows/filter_projects.py
  CONTRIBUTING.md
Labels: lgtm, needs-merge

#167 CI: Run all if event name is push
  .github/workflows/ci_examples.yml
  .github/workflows/filter_examples.py
  .github/workflows/filter_projects.py
Labels: needs-lgtm

#170 Update RELEASE.md
  RELEASE.md
Labels: needs-lgtm

#171 update firebase publisher proposal
  tfx_addons/firebase_publisher/README.md
Labels: lgtm, merge-ready

#174 HFModelPusher component proposal
  proposals/20220823-huggingface_model_pusher.md
Labels: lgtm, needs-merge

#177 fix: missing option --hook-type
  CONTRIBUTING.md
Labels: needs-lgtm

#163 Scaling Sampler by using row level probability
  proposals/20210721-sampling_component.md
  tfx_addons/sampling/README.md
  tfx_addons/sampling/RELEASE.md
  tfx_addons/sampling/__init__.py
  tfx_addons/sampling/component.py
  tfx_addons/sampling/component_test.py
  tfx_addons/sampling/executor.py
  tfx_addons/sampling/executor_test.py
  tfx_addons/sampling/spec.py
Labels: lgtm, merge-ready

#175 Add FirebasePublisher Implementation
  tfx_addons/firebase_publisher/__init__.py
  tfx_addons/firebase_publisher/component.py
  tfx_addons/firebase_publisher/component_test.py
  tfx_addons/firebase_publisher/executor.py
  tfx_addons/firebase_publisher/runner.py
  tfx_addons/firebase_publisher/runner_test.py
  tfx_addons/version.py
Labels: lgtm, merge-ready
