Repository tensorflow/tfx-addons, pull requests merged in 2022-05, with the labels that each got.

#132 FeastExampleGen
  .github/ci/.pre-commit-config.yaml
  .gitignore
  CODEOWNERS
  examples/fraud_feast/README.md
  examples/fraud_feast/feast_pipeline_local.py
  examples/fraud_feast/repo/.gitignore
  examples/fraud_feast/repo/driver_repo.py
  examples/fraud_feast/repo/feature_store.yaml
  examples/fraud_feast/requirements.txt
  setup.py
  tfx_addons/feast_examplegen/README.md
  tfx_addons/feast_examplegen/RELEASE.md
  tfx_addons/feast_examplegen/__init__.py
  tfx_addons/feast_examplegen/component.py
  tfx_addons/feast_examplegen/component_test.py
  tfx_addons/feast_examplegen/converters.py
  tfx_addons/feast_examplegen/executor.py
  tfx_addons/feast_examplegen/executor_test.py
  tfx_addons/feast_examplegen/protos/FeastConfig.proto
  tfx_addons/feast_examplegen/protos/feast/core/CoreService.proto
  tfx_addons/feast_examplegen/protos/feast/core/DataFormat.proto
  tfx_addons/feast_examplegen/protos/feast/core/DataSource.proto
  tfx_addons/feast_examplegen/protos/feast/core/Entity.proto
  tfx_addons/feast_examplegen/protos/feast/core/Feature.proto
  tfx_addons/feast_examplegen/protos/feast/core/FeatureService.proto
  tfx_addons/feast_examplegen/protos/feast/core/FeatureTable.proto
  tfx_addons/feast_examplegen/protos/feast/core/FeatureView.proto
  tfx_addons/feast_examplegen/protos/feast/core/FeatureViewProjection.proto
  tfx_addons/feast_examplegen/protos/feast/core/OnDemandFeatureView.proto
  tfx_addons/feast_examplegen/protos/feast/core/Registry.proto
  tfx_addons/feast_examplegen/protos/feast/core/Store.proto
  tfx_addons/feast_examplegen/protos/feast/types/EntityKey.proto
  tfx_addons/feast_examplegen/protos/feast/types/Field.proto
  tfx_addons/feast_examplegen/protos/feast/types/Value.proto
Labels: needs-lgtm

#136 Some minor clean ups before 0.2.0 initial candidate
  .github/workflows/ci.yml
  CONTRIBUTING.md
  README.md
  RELEASE.md
  tfx_addons/feature_selection/example/Examples.ipynb
  tfx_addons/feature_selection/nb/Example.ipynb
  tfx_addons/sampling/example/local_notebook.ipynb
  tfx_addons/schema_curation/example/taxi_example_colab.ipynb
  tfx_addons/version.py
Labels: needs-lgtm

#138 Bump version to 0.3.0dev0 as 0.2.0 is in rc0
  tfx_addons/version.py
Labels: lgtm, merge-ready

#135 Proposal for PandasTransform
  proposals/20220513-PandasTransform.md
Labels: lgtm, needs-merge

#140 Rcrowe fixing filename
  proposals/20220513-pandas_transform.md
Labels: lgtm, merge-ready

#142 Update README.md
  README.md
Labels: needs-lgtm

#143 Fix bad link in xgboost_evaluator
  README.md
Labels: needs-lgtm

#144 Cherry pick bot to backport changes
  .github/workflows/cherrypick.yml
  RELEASE.md
Labels: needs-lgtm

#116 Update examples for feature selection component
  tfx_addons/feature_selection/example/Examples.ipynb
  tfx_addons/feature_selection/example/Iris_example_colab.ipynb
  tfx_addons/feature_selection/example/Palmer_Penguins_example_colab.ipynb
  tfx_addons/feature_selection/example/Pima_Indians_Diabetes_example_colab.ipynb
  tfx_addons/feature_selection/example/modules/iris_module_file.py
  tfx_addons/feature_selection/example/modules/penguins_module.py
  tfx_addons/feature_selection/example/modules/pima_indians_module_file.py
  tfx_addons/feature_selection/module_file.py
Labels: lgtm, merge-ready

#145 Fix bad link in xgboost_evaluator
  README.md
Labels: lgtm, needs-merge
