Repository tensorflow/tfx-addons, pull requests merged in 2022-04, with the labels that each got.

#107 Release proposal
  .github/license-templates/LICENSE.txt
  .github/workflows/ci.yml
  .github/workflows/publish-to-test-pypi.yml
  README.md
  RELEASE.md
  setup.py
  tfx_addons/__init__.py
  tfx_addons/version.py
Labels: lgtm, needs-merge

#119 Remove pyarrow note
  .github/workflows/ci.yml
Labels: needs-lgtm

#108 TFX Message exit handler
  CODEOWNERS
  setup.py
  tfx_addons/message_exit_handler/README.md
  tfx_addons/message_exit_handler/RELEASE.md
  tfx_addons/message_exit_handler/__init__.py
  tfx_addons/message_exit_handler/component.py
  tfx_addons/message_exit_handler/component_test.py
  tfx_addons/message_exit_handler/constants.py
  tfx_addons/message_exit_handler/message_providers/__init__.py
  tfx_addons/message_exit_handler/message_providers/base_provider.py
  tfx_addons/message_exit_handler/message_providers/base_provider_test.py
  tfx_addons/message_exit_handler/message_providers/logging_provider.py
  tfx_addons/message_exit_handler/message_providers/logging_provider_test.py
  tfx_addons/message_exit_handler/message_providers/slack_provider.py
  tfx_addons/message_exit_handler/message_providers/slack_provider_test.py
  tfx_addons/utils/__init__.py
  tfx_addons/utils/test_utils.py
  tfx_addons/utils/test_utils_tests.py
Labels: lgtm, merge-ready

#121 Update release workflow
  .github/workflows/release.yml
  RELEASE.md
Labels: needs-lgtm

#122 Prepare 0.1.0rc0
  tfx_addons/version.py
Labels: needs-lgtm

#128 Add root packages to 0.1.0 candidate
  setup.py
Labels: lgtm, needs-merge

#131 Release 0.1.0
  tfx_addons/version.py
Labels: lgtm, merge-ready
